### ISSUE TITLE
How to add request logs to check if requests are routed through `proton-privoxy`?

### ISSUE THREAD

**Issue by kohane27** [walterl/proton-privoxy#42]
Hello there. Hope you're doing well. Thank you for creating `proton-privoxy`. This is the perfect application for me as I only need to use ProtonVPN for a few connections through `curl`.

## Description

I'm trying to add debug logs to see every request that is routed through `proton-privoxy`.

## Reproducible steps

`docker-compose.yml`:

```yml
version: "3"
services:
  proton-privoxy:
    image: walt3rl/proton-privoxy
    container_name: proton-privoxy
    environment:
      - PVPN_USERNAME=username
      - PVPN_PASSWORD=password
      - PVPN_TIER=0
      - PVPN_PROTOCOL=udp
      - PVPN_DEBUG=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/username/Downloads/proton-privoxy/debug.config:/etc/privoxy/config
    ports:
      - 8888:8080
    restart: unless-stopped
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
```

Basically, I have added `PVPN_DEBUG=1` and mounted host's `debug.config` to the container's `/etc/privoxy/config` to allow the container to use the `debug.config` file.

`debug.config`:

```
logfile /var/log/privoxy/logfile
debug 1
```

The reason for `debug.config` is because [6.2. Configuration Files Overview](https://www.privoxy.org/user-manual/configuration.html) has specified the following:

> For Unix, \*BSD and GNU/Linux, all configuration files are located in /etc/privoxy/ by default.
> The main configuration file is named config on GNU/Linux

According to [7.3.1. debug](https://www.privoxy.org/user-manual/config.html):

> A debug level of 1 is informative because it will show you each request as it happens.

When I run `docker-compose up -d && docker-compose logs -f`:

```
[+] Building 0.0s (0/0)                                                                             docker:default
[+] Running 2/2
 ✔ Network proton-privoxy_default  Created                                                                    0.1s
 ✔ Container proton-privoxy        Started                                                                    0.4s
proton-privoxy  | 2023-10-21 09:42:22,449 — protonvpn-cli — DEBUG — cli:89 — ###########################
proton-privoxy  | 2023-10-21 09:42:22,450 — protonvpn-cli — DEBUG — cli:90 — ### NEW PROCESS STARTED ###
proton-privoxy  | 2023-10-21 09:42:22,450 — protonvpn-cli — DEBUG — cli:91 — ###########################
proton-privoxy  | 2023-10-21 09:42:22,450 — protonvpn-cli — DEBUG — cli:92 — ['/usr/bin/protonvpn', 'refresh']
proton-privoxy  | 2023-10-21 09:42:22,450 — protonvpn-cli — DEBUG — cli:93 — USER: root
proton-privoxy  | 2023-10-21 09:42:22,450 — protonvpn-cli — DEBUG — cli:94 — CONFIG_DIR: /root/.pvpn-cli
...omitted...
proton-privoxy  | 2023-10-21 09:42:22,476 — protonvpn-cli — DEBUG — call_api:38 — Initiating API Call: https://api.protonvpn.ch/vpn/logicals
proton-privoxy  | 2023-10-21 09:42:24,746 — protonvpn-cli — DEBUG — call_api:67 — Successful json response
...omitted...
proton-privoxy  | 2023-10-21 09:42:56,181 — protonvpn-cli — DEBUG — set_config_value:135 — Writing last_update_check to [metadata] in config file
proton-privoxy  | Connecting to US-FREE#52 via UDP...
proton-privoxy  | Connected!
proton-privoxy  | 2023-10-21 09:42:56.242 7f84a02efb48 Info: Privoxy version 3.0.33
proton-privoxy  | 2023-10-21 09:42:56.242 7f84a02efb48 Info: Program name: privoxy
proton-privoxy  | 2023-10-21 09:42:56.243 7f84a02efb48 Info: Listening on port 8080 on IP address 0.0.0.0
```

To test:

```
curl --proxy http://127.0.0.1:8888 ifconfig.co/json | jq
```

## Expected behavior

However, nothing is reflected and updated in the log. The last line is still `Listening on port 8080 on IP address 0.0.0.0`.

I was hoping that when I run `curl --proxy http://127.0.0.1:8888 ifconfig.co/json | jq` on my main machine, the request is logged and reflected in `proton-privoxy` debug log (i.e., new entries under `Listening on port 8080 on IP address 0.0.0.0`).

Any input is much appreciated. Thank you.
