### ISSUE TITLE
Docker-Compose Won't Connect 

### ISSUE THREAD

**Issue by MyVizDrake** [walterl/proton-privoxy#56]
Docker environment is running in a jail on TrueNAS SCALE (23.10)

Docker-Compose
```
services:
  proton-privoxy:
    image: walt3rl/proton-privoxy
    container_name: proton-privoxy
    environment:
      - PVPN_USERNAME=<userid>
      - PVPN_PASSWORD=<password>
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8080
    restart: unless-stopped
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
networks: {}

```
Docker Terminal Output when deploying the container
```
proton-privoxy  | Connecting to US-NJ#59 via UDP...
proton-privoxy  | Traceback (most recent call last):
proton-privoxy  |   File "/usr/bin/protonvpn", line 33, in <module>
proton-privoxy  |     sys.exit(load_entry_point('protonvpn-cli==2.2.12', 'console_scripts', 'protonvpn')())
proton-privoxy  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 72, in main
proton-privoxy  |     cli()
proton-privoxy  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 121, in cli
proton-privoxy  |     connection.fastest(protocol)
proton-privoxy  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 181, in fastest
proton-privoxy  |     openvpn_connect(fastest_server, protocol)
proton-privoxy  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 517, in openvpn_connect
proton-privoxy  |     manage_ipv6("disable")
proton-privoxy  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 677, in manage_ipv6
proton-privoxy  |     ip6tables_rules = subprocess.run(["ip6tables-save"],
proton-privoxy  |   File "/usr/lib/python3.10/subprocess.py", line 503, in run
proton-privoxy  |     with Popen(*popenargs, **kwargs) as process:
proton-privoxy  |   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
proton-privoxy  |     self._execute_child(args, executable, preexec_fn, close_fds,
proton-privoxy  |   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
proton-privoxy  |     raise child_exception_type(errno_num, err_msg, err_filename)
proton-privoxy  | FileNotFoundError: [Errno 2] No such file or directory: 'ip6tables-save'
proton-privoxy  | 2024-09-05 09:38:42.474 7fa7b198fb48 Info: Privoxy version 3.0.33
proton-privoxy  | 2024-09-05 09:38:42.474 7fa7b198fb48 Info: Program name: privoxy
proton-privoxy  | 2024-09-05 09:38:42.474 7fa7b198fb48 Info: Listening on port 8080 on IP address 0.0.0.0
```

ipv6 iptables is available in the docker host / jail

![image](https://github.com/user-attachments/assets/96c9753f-1452-4046-b49d-9a558f92e96b)

Thoughts?
